baseurl = "http://research.mlabdance.com/"
languageCode = "en-us"
title = "Digital Dance Group"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name        = "kosakasakas"
	description = "森島研究室ダンス班"
    thumbnail   = "thumbnail.png"
    image       = "image.png"

	# Navigation
	[params.navigation]
		brand = "Digital Dance Group"

		[params.navigation.links]
            vision    = "Vision"
            news      = "News"
			keywords  = "Keywords"
            projects  = "Projects"
            people    = "People"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Digital Dance Group"
		subtitle   = "supported by Morishima Lab. at Waseda University."
		buttonText = "▼"

	# Vision section
	[params.vision]
		headline    = "Vision"
		description = "従来、楽曲のビジュアライゼーションシステムは、波形や周波数スペクトログラムを用いたものに留まり、楽曲の持つ印象を視覚的に表現する術を持たなかった。では、楽曲の印象を視覚化するものとは何か。私たちはその答えが” ダンス” にあるのではないかと考えている。ダンスとは，アーティストがその楽曲を理解し，身体動作で表現する試みの１つであり，リスナーがその楽曲を視覚的に理解する上でも重要な要素となる。そこで私たちは，楽曲の印象をダンスでビジュアル化することで楽曲をより深く理解できるのではないかと考えた。以上を踏まえ、私たちは楽曲の持つ特徴や印象にマッチした3Dキャラクターのダンスアニメーションを自動で生成するシステムを提案し，実装を行う。本プロジェクトは，従来にはなかった新しい音楽鑑賞のスタイルを提示し，リスナーが音楽をより楽しむと同時に、能動的に音楽を理解しようとするきっかけを生み出すものである．"
		buttonText  = "See Projects"

	# Keywords section
	[params.keywords]
		headline = "Keywords"
        description = "本グループは森島研究室の中でも，特に身体の動きや感情表出に関する技術に注目し，プログラミングによる計算機の力と人の創造性を組み合わせたアイデア，研究を通じたあらゆる問題解決に挑戦していきます．"

        [[params.keywords.list]]
            icon = "fa-music"
            title = "Synchronization between Music and Motion"
            description = "音楽と動きのシンクロ"

		[[params.keywords.list]]
            icon = "fa-newspaper-o"
            title = "Music Structure and Feature Analysis"
            description = "楽曲構造・特徴量解析"

        [[params.keywords.list]]
			icon = "fa-hand-o-right"
			title = "Motion Analysis"
			description = "モーション解析"

        [[params.keywords.list]]
            icon = "fa-heart"
            title = "Emotion Analysis and Visualization"
            description = "感情分析, ビジュアライゼーション"


    # News modals
	[params.news]
        headline = "News"
        description = "デジタルダンスグループの活動にまつわる最新情報をお知らせします. "

	[params.news.modal]
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # Portfolio modals
	[params.portfolio]
        headline = "Portfolio"

	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # Projects
	[params.projects]
        headline = "Projects"
        description = "デジタルダンスグループのプロジェクトの一部を紹介します."

	[params.projects.modal]
        client = "Client"
        keyword = "Keyword"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact Us"
		description = "デジタルダンスグループは，人の動きを初めとする様々なモーション解析技術を用いた問題解決に日々取り組んでいます．何かコラボレーションできそうなきっかけがあればぜひお声かけお願い致します．"
		phone = "+81-3-5286-3510"
		email = "iwanao731@gmail.com"
        twitter = "kosakasakas"

    # People section
	[params.people]
		headline    = "People"
        description = ""
        category1   = "Members"
        category2   = "OB･OG"

        [[params.people.member]]
            img = "euclid_c.png"
            name = "岩本 尚也"
            description = "コンセプト，物理ベースキャラクタアニメーション"

        [[params.people.member]]
            img = "wakana_c.png"
            name = "朝比奈 わかな"
            description = "表情生成，モーション生成"

        [[params.people.member]]
            img = "kakitsuka.png"
            name = "柿塚 亮"
            description = "モーションの自動生成"

        [[params.people.member]]
            img = "nakatsuka.png"
            name = "中塚 貴之"
            description = "モーション解析"

        [[params.people.obog]]
            img = "naru_c.png"
            name = "岡田 成美"
            description = "ダンサー, ダンスモーションのフィルター開発， セグメンテーション分割手法"

        [[params.people.obog]]
            img = "masutaro_c.png"
            name = "増田 太郎"
            description = "楽曲解析"

        [[params.people.obog]]
            img = "kakuto_c.png"
            name = "後藤 岳人"
            description = "キャラクターコントロール技術"


